# params.yaml

# Cross-validation settings
cv_settings:
  n_splits: 5
  shuffle: true
  random_state: 42

# Model hyperparameters
model_params:
  linear_regression:
    fit_intercept: true

  decision_tree:
    max_depth: 10
    min_samples_split: 5
    min_samples_leaf: 2
    random_state: 42
    criterion: squared_error

  random_forest:
    n_estimators: 100
    max_depth: 12
    min_samples_split: 4
    min_samples_leaf: 2
    random_state: 42
    criterion: squared_error

  knn:
    n_neighbors: 5
    weights: uniform
    algorithm: auto

  stacking_regressor:
    final_estimator: linear_regression  # Use LinearRegression as meta-learner
    cv: 5
    n_jobs: -1

# Target Column
target_column: default_risk_score