artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_data_file: notebook/data/default.csv
  local_data_file: artifacts/data_ingestion/default.csv

data_validation:
  root_dir: artifacts/data_validation
  data_path: artifacts/data_ingestion/default.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/default.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: artifacts/model_trainer/model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
  mlflow_uri: https://dagshub.com/klan86at/Default-risk-prediction.mlflow
  experiment_name: DefaultRiskPrediction